// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ujdgcxdkbzmcfoeoxrjz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVqZGdjeGRrYnptY2ZvZW94cmp6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0MzEwOTYsImV4cCI6MjA3MzAwNzA5Nn0.QNO6VkxKDM4TUFrRG_A9mp0FigPjmBCXvmarCNsTPEs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});